version: "3.8"

services:
  postgres:
    image: "postgres:16"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "hamstats"
      POSTGRES_PASSWORD: "hamstats"
      POSTGRES_DB: "hamstats"

volumes:
    postgres_data: {}
