// <auto-generated />
using System;
using HamStats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HamStats.Data.Migrations
{
    [DbContext(typeof(HamStatsDbContext))]
    partial class HamStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HamStats.Data.Models.Antenna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Antennas");
                });

            modelBuilder.Entity("HamStats.Data.Models.AntennaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AntennaLogs");
                });

            modelBuilder.Entity("HamStats.Data.Models.CallsignEntry", b =>
                {
                    b.Property<string>("Callsign")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Callsign");

                    b.ToTable("Callsigns");
                });

            modelBuilder.Entity("HamStats.Data.Models.CallsignPrefix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Continent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Prefix");

                    b.ToTable("CallsignPrefixes");
                });

            modelBuilder.Entity("HamStats.Data.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromCall")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gridsquare")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("N1MMContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RadioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RxFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToCall")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TxFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("N1MMContactId")
                        .IsUnique();

                    b.HasIndex("RadioId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("HamStats.Data.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Radio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("HamStats.Data.Models.N1MMContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryPrefix")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromCall")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("N1MMId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Receive")
                        .HasColumnType("TEXT");

                    b.Property<string>("RxFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sent")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToCall")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TxFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("N1MMContacts");
                });

            modelBuilder.Entity("HamStats.Data.Models.N1MMRadio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("RadioName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RadioNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RxFrequency")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TxFrequency")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VFOId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VFOId")
                        .IsUnique();

                    b.ToTable("N1MMRadios");
                });

            modelBuilder.Entity("HamStats.Data.Models.Radio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Radios");
                });

            modelBuilder.Entity("HamStats.Data.Models.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrlSection")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assisted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bands")
                        .HasColumnType("TEXT");

                    b.Property<string>("Call")
                        .HasColumnType("TEXT");

                    b.Property<string>("Club")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contest")
                        .HasColumnType("TEXT");

                    b.Property<string>("CqZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("DxccCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grid6")
                        .HasColumnType("TEXT");

                    b.Property<string>("Iaruzone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ops")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overlay")
                        .HasColumnType("TEXT");

                    b.Property<string>("Power")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stprvoth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transmitter")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("HamStats.Data.Models.ScoreBreakdown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QSOs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScoreId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScoreId");

                    b.ToTable("ScoreBreakdowns");
                });

            modelBuilder.Entity("HamStats.Data.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("HamStats.Data.Models.VFO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RadioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RxFrequency")
                        .HasColumnType("TEXT");

                    b.Property<string>("TxFrequency")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RadioId");

                    b.ToTable("VFO");
                });

            modelBuilder.Entity("HamStats.Data.Models.Contact", b =>
                {
                    b.HasOne("HamStats.Data.Models.N1MMContact", "N1MMContact")
                        .WithOne("Contact")
                        .HasForeignKey("HamStats.Data.Models.Contact", "N1MMContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamStats.Data.Models.Radio", "Radio")
                        .WithMany("Contacts")
                        .HasForeignKey("RadioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("N1MMContact");

                    b.Navigation("Radio");
                });

            modelBuilder.Entity("HamStats.Data.Models.N1MMRadio", b =>
                {
                    b.HasOne("HamStats.Data.Models.VFO", "VFO")
                        .WithOne("N1MMRadio")
                        .HasForeignKey("HamStats.Data.Models.N1MMRadio", "VFOId");

                    b.Navigation("VFO");
                });

            modelBuilder.Entity("HamStats.Data.Models.ScoreBreakdown", b =>
                {
                    b.HasOne("HamStats.Data.Models.Score", "Score")
                        .WithMany("Breakdown")
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Score");
                });

            modelBuilder.Entity("HamStats.Data.Models.VFO", b =>
                {
                    b.HasOne("HamStats.Data.Models.Radio", "Radio")
                        .WithMany("VFOs")
                        .HasForeignKey("RadioId");

                    b.Navigation("Radio");
                });

            modelBuilder.Entity("HamStats.Data.Models.N1MMContact", b =>
                {
                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("HamStats.Data.Models.Radio", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("VFOs");
                });

            modelBuilder.Entity("HamStats.Data.Models.Score", b =>
                {
                    b.Navigation("Breakdown");
                });

            modelBuilder.Entity("HamStats.Data.Models.VFO", b =>
                {
                    b.Navigation("N1MMRadio");
                });
#pragma warning restore 612, 618
        }
    }
}
